/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/

#include <iostream>
using namespace std;

int NumA = 1;
int NumB = 1;
int Sum = 0;
int Out = 0;

int main(){

	while(NumA < 4000000){
		Sum = NumA + NumB;
		NumB = NumA;
		NumA = Sum;
		if(Sum%2 == 0){
			Out += Sum;
		}
		cout << Sum % 2 << " : ";		//Jen info
		cout << NumA << endl;
	}
	cout << Out << endl;				//Vysledek
	return 0;
}